# config/packages/security.yaml

security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api:
            pattern: ^/api/
            provider: app_user_provider
            stateless: true
            custom_authenticator: App\Security\ApiTokenAuthenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout
                target: home
            custom_authenticator: App\Security\LoginFormAuthenticator

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/dashboard, roles: ROLE_USER }
        #- { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
