<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPMxRxyo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPMxRxyo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPMxRxyo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPMxRxyo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPMxRxyo\App_KernelDevDebugContainer([
    'container.build_hash' => 'PMxRxyo',
    'container.build_id' => '3de952a6',
    'container.build_time' => 1716192796,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPMxRxyo');
